update builder

diff --git a/builder/Dockerfile b/builder/Dockerfile
--- a/builder/Dockerfile
+++ b/builder/Dockerfile
@@ -10,7 +10,7 @@ RUN set -ex \
     && apt-get install software-properties-common -y -qq --no-install-recommends \
     && apt-get update \
     && apt-get install -y -qq --no-install-recommends \
-        curl jq unzip wget \
+        curl jq unzip wget apt-utils tar \
     && rm -rf /var/lib/apt/lists/*
 
 # Add new repo
@@ -46,16 +46,87 @@ RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/s
     && chmod 700 get_helm.sh \
     && ./get_helm.sh
 
+# Install Helmfile
+RUN helm plugin install https://github.com/databus23/helm-diff
+
 # Install Node 16
 RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
     && apt-get install -y nodejs \
     && node -v
 
+# Install Yarn
+RUN npm install --global yarn \
+    && yarn --version
+
 # Install Docker
 RUN curl -fsSL https://get.docker.com -o get-docker.sh && \
     sh get-docker.sh && \
     chmod ug+s /usr/bin/docker && \
-    rm ./get-docker.sh \
+    rm ./get-docker.sh
+
+#****************      JAVA     ****************************************************
+ENV JAVA_17_HOME="/usr/lib/jvm/java-17-amazon-corretto" \
+    JDK_17_HOME="/usr/lib/jvm/java-17-amazon-corretto" \
+    JRE_17_HOME="/usr/lib/jvm/java-17-amazon-corretto"
+ARG ANT_VERSION=1.10.13
+ARG MAVEN_HOME="/opt/maven"
+ARG MAVEN_VERSION=3.9.1
+ARG GRADLE_VERSION=8.0.2
+ARG SBT_VERSION=1.8.2
+ARG GRADLE_PATH="$SRC_DIR/gradle"
+ARG ANT_DOWNLOAD_SHA512="de4ac604629e39a86a306f0541adb3775596909ad92feb8b7de759b1b286417db24f557228737c8b902d6abf722d2ce5bb0c3baa3640cbeec3481e15ab1958c9"
+ARG MAVEN_DOWNLOAD_SHA512="d3be5956712d1c2cf7a6e4c3a2db1841aa971c6097c7a67f59493a5873ccf8c8b889cf988e4e9801390a2b1ae5a0669de07673acb090a083232dbd3faf82f3e3"
+ARG GRADLE_DOWNLOADS_SHA256="47a5bfed9ef814f90f8debcbbb315e8e7c654109acd224595ea39fca95c5d4da 8.0.2"
+ARG SBT_DOWNLOAD_SHA256="1f65344da074dbd66dfefa93c0eff8d319d772e5cad47fcbeb6ae178bbdf4686"
+
+ARG MAVEN_CONFIG_HOME="/root/.m2"
+
+ENV JAVA_HOME="$JAVA_17_HOME" \
+    JDK_HOME="$JDK_17_HOME" \
+    JRE_HOME="$JRE_17_HOME"
+
+ENV PATH="${PATH}:/opt/tools"
+
+RUN set -ex \
+    && apt-get update \
+    && apt-get install -y -qq software-properties-common apt-utils \
+    # Install Corretto 17
+    && wget -qO- https://apt.corretto.aws/corretto.key | apt-key add - \
+    && add-apt-repository 'deb https://apt.corretto.aws stable main' \
+    && apt-get update \
+    && apt-get install -y -qq java-17-amazon-corretto-jdk \
+    && apt-get install -y -qq --no-install-recommends ca-certificates-java \
+    # Ensure Java cacerts symlink points to valid location
+    && update-ca-certificates -f \
+    && dpkg --add-architecture i386 \
+    && apt-get update \
+    && for tool_path in $JAVA_HOME/bin/*; do \
+          tool=`basename $tool_path`; \
+          update-alternatives --install /usr/bin/$tool $tool $tool_path 10000; \
+          update-alternatives --set $tool $tool_path; \
+        done \
+     && rm $JAVA_HOME/lib/security/cacerts && ln -s /etc/ssl/certs/java/cacerts $JAVA_HOME/lib/security/cacerts \
+    # Install Ant
+    && curl -LSso /var/tmp/apache-ant-$ANT_VERSION-bin.tar.gz https://archive.apache.org/dist/ant/binaries/apache-ant-$ANT_VERSION-bin.tar.gz  \
+    && echo "$ANT_DOWNLOAD_SHA512 /var/tmp/apache-ant-$ANT_VERSION-bin.tar.gz" | sha512sum -c - \
+    && tar -xzf /var/tmp/apache-ant-$ANT_VERSION-bin.tar.gz -C /opt \
+    && rm /var/tmp/apache-ant-$ANT_VERSION-bin.tar.gz \
+    && update-alternatives --install /usr/bin/ant ant /opt/apache-ant-$ANT_VERSION/bin/ant 10000
+
+RUN set -ex \
+    # Install Maven
+    && mkdir -p $MAVEN_HOME \
+    && curl -LSso /var/tmp/apache-maven-$MAVEN_VERSION-bin.tar.gz https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz \
+    && echo "$MAVEN_DOWNLOAD_SHA512 /var/tmp/apache-maven-$MAVEN_VERSION-bin.tar.gz" | sha512sum -c - \
+    && tar xzf /var/tmp/apache-maven-$MAVEN_VERSION-bin.tar.gz -C $MAVEN_HOME --strip-components=1 \
+    && rm /var/tmp/apache-maven-$MAVEN_VERSION-bin.tar.gz \
+    && update-alternatives --install /usr/bin/mvn mvn /opt/maven/bin/mvn 10000 \
+    && mkdir -p $MAVEN_CONFIG_HOME
+
+# Cleanup
+RUN rm -fr /var/lib/apt/lists/* /tmp/* /var/tmp/* \
+    && apt-get clean
+#****************     END JAVA     ****************************************************
 
 # Remove unused files and other
 RUN rm -rf /var/lib/apt/lists/*
